language: node_js
node_js:
   - "node" # Latest node version
   - "lts/*" # Latest LTS version
   - "10"
   - "8.10"

before_install: if [[ `npm -v` != 6* ]]; then npm i -g npm@6.4.1; fi

install:
   - wget https://github.com/gohugoio/hugo/releases/download/v0.55.6/hugo_0.55.6_Linux-64bit.tar.gz -O /tmp/hugo.tar.gz
   - pushd /tmp
   - tar -xzvf hugo.tar.gz
   - popd
   - chmod +x /tmp/hugo
   - /tmp/hugo version
   - git clone https://github.com/gohugoio/hugoBasicExample.git /tmp/hugoBasicExample
   - npm ci

script:
   - node --version
   - npm --version
   - grunt standards
   - commitlint-travis
   - grunt clean build
   - npm run test:ci
   - cd /tmp/hugoBasicExample
   - mkdir themes
   - ln -s $TRAVIS_BUILD_DIR themes/substratum
   - /tmp/hugo -t substratum

deploy:
   provider: pages
   local_dir: /tmp/hugoBasicExample/public
   skip_cleanup: true
   github_token: $GITHUB_TOKEN # Set in the settings page of the repository, as a secure variable
   committer_from_gh: true
   keep_history: true
   on:
      branch: master
      node: '8.10'

# For code coverage:
after_success:
   cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
